# Site settings
title: "Saman's Music Research"
description: "Music production research, gear analysis, and techniques by Saman - a software engineer and music enthusiast in London"
baseurl: "/music-research"
url: "https://yourusername.github.io"

# Author information
author:
  name: "Saman"
  bio: "Software engineer and music production enthusiast based in London. Researching music gear, sampling techniques, and production methods."
  location: "London, UK"
  
# Build settings
markdown: kramdown
highlighter: rouge
# theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections for better organization
collections:
  guides:
    output: true
    permalink: /:collection/:name/

# Default layouts for different content types
defaults:
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Tag pages configuration
tag_page_layout: tag
tag_page_dir: tags

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
